[package]
name = "gamlss-transform"
version.workspace = true
edition.workspace = true
description = "Target transforms for GAMLSS modeling"
license.workspace = true
authors.workspace = true
repository.workspace = true
documentation = "https://docs.rs/gamlss-transform"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
include = [
    "src/**/*",
    "doc-assets/*",
    "Cargo.toml",
    "README.md",
]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "doc-assets/katex-header.html"]

[dependencies]
gamlss-special.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true

[lints]
workspace = true
