[package]
name = "gamlss-datasets"
version.workspace = true
edition.workspace = true
description = "Small built-in datasets for GAMLSS examples and experimentation"
publish = false
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
build = "build.rs"

[features]
default = []
rand = ["dep:rand", "dep:rand_distr"]

[dependencies]
rand = { workspace = true, optional = true }
rand_distr = { workspace = true, optional = true }

[lints]
workspace = true
